### ISSUE TITLE
Sometimes unicode sometimes str

### ISSUE THREAD

**Issue by ghost** [IlyaSkriblovsky/txredisapi#75]
It appears that sometimes the commands will return unicode and sometimes standard strings. i have no idea if this is intended or not but it seems to become a standard string when it contains characters that is not allowed in unicode. This is annoying when you for example get all members of a set and they do not have the same type. Tested on Python version 2.7.6

**Comment by offero** [comment]
When will it return a string instead of unicode if charset='utf-8'?
